//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NureTimetable.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NureTimetable.Core.Localization.LN", typeof(LN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for displaying groups schedule for.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE Timetable.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful links.
        /// </summary>
        public static string HelpfulLinks {
            get {
                return ResourceManager.GetString("HelpfulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have experience with Xamarin apps development and you are willing to help, submit to: .
        /// </summary>
        public static string HelpWanted {
            get {
                return ResourceManager.GetString("HelpWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string NureHomepage {
            get {
                return ResourceManager.GetString("NureHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE official webpages: .
        /// </summary>
        public static string NureWebpages {
            get {
                return ResourceManager.GetString("NureWebpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors.
        /// </summary>
        public static string ShowErrors {
            get {
                return ResourceManager.GetString("ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student NURE: .
        /// </summary>
        public static string StudentNure {
            get {
                return ResourceManager.GetString("StudentNure", resourceCulture);
            }
        }
    }
}
