//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NureTimetable.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NureTimetable.Core.Localization.LN", typeof(LN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group to view timetable..
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and will always be..
        /// </summary>
        public static string AndWillAlwaysBe {
            get {
                return ResourceManager.GetString("AndWillAlwaysBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for displaying groups schedule for.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE Timetable.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display lesson.
        /// </summary>
        public static string DisplayLesson {
            get {
                return ResourceManager.GetString("DisplayLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display lesson types for this lesson:.
        /// </summary>
        public static string DisplayLessonsForTypes {
            get {
                return ResourceManager.GetString("DisplayLessonsForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable has no classes to display (maybe it&apos;s empty)..
        /// </summary>
        public static string EmptyLessonsList {
            get {
                return ResourceManager.GetString("EmptyLessonsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom: {0}.
        /// </summary>
        public static string EventClassroom {
            get {
                return ResourceManager.GetString("EventClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day: {0}.
        /// </summary>
        public static string EventDay {
            get {
                return ResourceManager.GetString("EventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher: {0}.
        /// </summary>
        public static string EventTeacher {
            get {
                return ResourceManager.GetString("EventTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher: not found.
        /// </summary>
        public static string EventTeacherNotFound {
            get {
                return ResourceManager.GetString("EventTeacherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0} - {1}.
        /// </summary>
        public static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for group {0} saved successfully..
        /// </summary>
        public static string GroupSettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("GroupSettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful links.
        /// </summary>
        public static string HelpfulLinks {
            get {
                return ResourceManager.GetString("HelpfulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have experience with Xamarin apps development and you are willing to help, submit to: .
        /// </summary>
        public static string HelpWanted {
            get {
                return ResourceManager.GetString("HelpWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is free .
        /// </summary>
        public static string IsFree {
            get {
                return ResourceManager.GetString("IsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes: .
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string NureHomepage {
            get {
                return ResourceManager.GetString("NureHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE official webpages: .
        /// </summary>
        public static string NureWebpages {
            get {
                return ResourceManager.GetString("NureWebpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved groups.
        /// </summary>
        public static string SavedGroups {
            get {
                return ResourceManager.GetString("SavedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings.
        /// </summary>
        public static string SavingSettings {
            get {
                return ResourceManager.GetString("SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors.
        /// </summary>
        public static string ShowErrors {
            get {
                return ResourceManager.GetString("ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student NURE: .
        /// </summary>
        public static string StudentNure {
            get {
                return ResourceManager.GetString("StudentNure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank.
        /// </summary>
        public static string Thank {
            get {
                return ResourceManager.GetString("Thank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big thank.
        /// </summary>
        public static string Thank2 {
            get {
                return ResourceManager.GetString("Thank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge thank.
        /// </summary>
        public static string Thank3 {
            get {
                return ResourceManager.GetString("Thank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app .
        /// </summary>
        public static string ThisApp {
            get {
                return ResourceManager.GetString("ThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        public static string Timetable {
            get {
                return ResourceManager.GetString("Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable display.
        /// </summary>
        public static string TimetableDisplay {
            get {
                return ResourceManager.GetString("TimetableDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to display timetable.
        /// </summary>
        public static string TimetableDisplayError {
            get {
                return ResourceManager.GetString("TimetableDisplayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until break: {0}.
        /// </summary>
        public static string TimeUntilBreak {
            get {
                return ResourceManager.GetString("TimeUntilBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until {0} - {1}: {2}.
        /// </summary>
        public static string TimeUntilLesson {
            get {
                return ResourceManager.GetString("TimeUntilLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait....
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contribution supports development and doesn&apos;t let me fall into oblivion..
        /// </summary>
        public static string YourContribution {
            get {
                return ResourceManager.GetString("YourContribution", resourceCulture);
            }
        }
    }
}
