//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NureTimetable.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NureTimetable.Core.Localization.LN", typeof(LN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add event to calendar.
        /// </summary>
        public static string AddingEventToCalendarFail {
            get {
                return ResourceManager.GetString("AddingEventToCalendarFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been added to calendar.
        /// </summary>
        public static string AddingEventToCalendarSuccess {
            get {
                return ResourceManager.GetString("AddingEventToCalendarSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding timetable.
        /// </summary>
        public static string AddingTimetable {
            get {
                return ResourceManager.GetString("AddingTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to calendar.
        /// </summary>
        public static string AddingToCalendarTitle {
            get {
                return ResourceManager.GetString("AddingToCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to calendar.
        /// </summary>
        public static string AddToCalendar {
            get {
                return ResourceManager.GetString("AddToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to selected.
        /// </summary>
        public static string AddToSelected {
            get {
                return ResourceManager.GetString("AddToSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All events are shown.
        /// </summary>
        public static string AllEventsShown {
            get {
                return ResourceManager.GetString("AllEventsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and will always be..
        /// </summary>
        public static string AndWillAlwaysBe {
            get {
                return ResourceManager.GetString("AndWillAlwaysBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NURE Timetable.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask every time.
        /// </summary>
        public static string AskEveryTime {
            get {
                return ResourceManager.GetString("AskEveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For lessons management, you need to download timetable first..
        /// </summary>
        public static string AtFirstLoadTimetable {
            get {
                return ResourceManager.GetString("AtFirstLoadTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At time of event.
        /// </summary>
        public static string AtTimeOfEvent {
            get {
                return ResourceManager.GetString("AtTimeOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoupdate.
        /// </summary>
        public static string Autoupdate {
            get {
                return ResourceManager.GetString("Autoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update selected timetables.
        /// </summary>
        public static string AutoupdateDescription {
            get {
                return ResourceManager.GetString("AutoupdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoupdate failed. Try updating timetable manually..
        /// </summary>
        public static string AutoupdateFailed {
            get {
                return ResourceManager.GetString("AutoupdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting data from cist.nure.ua.
        ///Try again later, or try using different WiFi network or mobile internet connection..
        /// </summary>
        public static string CannotGetDataFromCist {
            get {
                return ResourceManager.GetString("CannotGetDataFromCist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action.
        /// </summary>
        public static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose calendar:.
        /// </summary>
        public static string ChooseCalendar {
            get {
                return ResourceManager.GetString("ChooseCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose display mode:.
        /// </summary>
        public static string ChooseDisplayMode {
            get {
                return ResourceManager.GetString("ChooseDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much load on cist.nure.ua. Please try again later..
        /// </summary>
        public static string CistException {
            get {
                return ResourceManager.GetString("CistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default calendar.
        /// </summary>
        public static string DefaultCalendar {
            get {
                return ResourceManager.GetString("DefaultCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display lesson.
        /// </summary>
        public static string DisplayLesson {
            get {
                return ResourceManager.GetString("DisplayLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display teachers for this lesson:.
        /// </summary>
        public static string DisplayLessonsForTeachers {
            get {
                return ResourceManager.GetString("DisplayLessonsForTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display lesson types for this lesson:.
        /// </summary>
        public static string DisplayLessonsForTypes {
            get {
                return ResourceManager.GetString("DisplayLessonsForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nure.ua email.
        /// </summary>
        public static string DlNureEmail {
            get {
                return ResourceManager.GetString("DlNureEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL Nure Integration.
        /// </summary>
        public static string DlNureIntegration {
            get {
                return ResourceManager.GetString("DlNureIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL Nure integration enables:
        ///- Attendance management for ongoing event
        ///- Automatic lesson filtering
        ///
        ///Credentials are stored locally..
        /// </summary>
        public static string DlNureIntegrationDescription {
            get {
                return ResourceManager.GetString("DlNureIntegrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL Nure lesson Id:.
        /// </summary>
        public static string DlNureLessonId {
            get {
                return ResourceManager.GetString("DlNureLessonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: {0} ({1}).
        /// </summary>
        public static string DlNureLoggedIn {
            get {
                return ResourceManager.GetString("DlNureLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned off.
        /// </summary>
        public static string DlNureSignedOut {
            get {
                return ResourceManager.GetString("DlNureSignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable has no lessons to display (maybe it&apos;s empty)..
        /// </summary>
        public static string EmptyLessonsList {
            get {
                return ResourceManager.GetString("EmptyLessonsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search returned no results.
        ///To update the list, click on the button in the upper right corner..
        /// </summary>
        public static string EmptyUniversityInfoSearch {
            get {
                return ResourceManager.GetString("EmptyUniversityInfoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name....
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson settings for &quot;{0}&quot; saved successfully..
        /// </summary>
        public static string EntityLessonSettingsSaved {
            get {
                return ResourceManager.GetString("EntityLessonSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room: {0}.
        /// </summary>
        public static string EventClassroom {
            get {
                return ResourceManager.GetString("EventClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        public static string EventDay {
            get {
                return ResourceManager.GetString("EventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups: {0}.
        /// </summary>
        public static string EventGroups {
            get {
                return ResourceManager.GetString("EventGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string EventsLeft {
            get {
                return ResourceManager.GetString("EventsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes total.
        /// </summary>
        public static string EventsTotal {
            get {
                return ResourceManager.GetString("EventsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers: {0}.
        /// </summary>
        public static string EventTeachers {
            get {
                return ResourceManager.GetString("EventTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0} - {1}.
        /// </summary>
        public static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the new version, the data storage structure has changed. An application needs to convert data from the old format to the new one. Click OK to complete the upgrade..
        /// </summary>
        public static string FinishingUpdateDescription {
            get {
                return ResourceManager.GetString("FinishingUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing update.
        /// </summary>
        public static string FinishingUpdateTitle {
            get {
                return ResourceManager.GetString("FinishingUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application does not have sufficient rights to perform this action.
        /// </summary>
        public static string InsufficientRights {
            get {
                return ResourceManager.GetString("InsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is free .
        /// </summary>
        public static string IsFree {
            get {
                return ResourceManager.GetString("IsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson info.
        /// </summary>
        public static string LessonInfo {
            get {
                return ResourceManager.GetString("LessonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson management.
        /// </summary>
        public static string LessonManagement {
            get {
                return ResourceManager.GetString("LessonManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LessonName {
            get {
                return ResourceManager.GetString("LessonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find lesson. It&apos;s possible, you don&apos;t have access to it. 
        ///Try adding lesson id manually on &quot;Lesson management&quot; page..
        /// </summary>
        public static string LessonNotFound {
            get {
                return ResourceManager.GetString("LessonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons management.
        /// </summary>
        public static string LessonsManagement {
            get {
                return ResourceManager.GetString("LessonsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: {0} ({1}).
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes before.
        /// </summary>
        public static string MinutesBefore {
            get {
                return ResourceManager.GetString("MinutesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextEvent {
            get {
                return ResourceManager.GetString("NextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson doesn&apos;t have an attendance module.
        /// </summary>
        public static string NoAttendanceModule {
            get {
                return ResourceManager.GetString("NoAttendanceModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no saved timetable..
        /// </summary>
        public static string NoSavedTimetables {
            get {
                return ResourceManager.GetString("NoSavedTimetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes: .
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select timetable to display..
        /// </summary>
        public static string NoTimetable {
            get {
                return ResourceManager.GetString("NoTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        ///To update, click on the button in the upper right corner..
        /// </summary>
        public static string NoUniversityInfo {
            get {
                return ResourceManager.GetString("NoUniversityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an event.
        /// </summary>
        public static string NoUpcomingEvent {
            get {
                return ResourceManager.GetString("NoUpcomingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open attendance page.
        /// </summary>
        public static string OpenAttendance {
            get {
                return ResourceManager.GetString("OpenAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other settings.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, purchase failed..
        /// </summary>
        public static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app.
        /// </summary>
        public static string RateTheApp {
            get {
                return ResourceManager.GetString("RateTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string RussianLanguage {
            get {
                return ResourceManager.GetString("RussianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved timetables.
        /// </summary>
        public static string SavedTimetables {
            get {
                return ResourceManager.GetString("SavedTimetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings.
        /// </summary>
        public static string SavingSettings {
            get {
                return ResourceManager.GetString("SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected events are shown.
        /// </summary>
        public static string SelectedEventsShown {
            get {
                return ResourceManager.GetString("SelectedEventsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only this one.
        /// </summary>
        public static string SelectOneEntity {
            get {
                return ResourceManager.GetString("SelectOneEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson settings.
        /// </summary>
        public static string SetUpLessonDisplay {
            get {
                return ResourceManager.GetString("SetUpLessonDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all errors.
        /// </summary>
        public static string ShowErrors {
            get {
                return ResourceManager.GetString("ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show today.
        /// </summary>
        public static string ShowToday {
            get {
                return ResourceManager.GetString("ShowToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics:.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide lessons that are not present on dl.nure.ua?.
        /// </summary>
        public static string SyncDlNureLessonsMessage {
            get {
                return ResourceManager.GetString("SyncDlNureLessonsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofiltration.
        /// </summary>
        public static string SyncDlNureLessonsTitle {
            get {
                return ResourceManager.GetString("SyncDlNureLessonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say thank you.
        /// </summary>
        public static string Thank {
            get {
                return ResourceManager.GetString("Thank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say big thank you.
        /// </summary>
        public static string Thank2 {
            get {
                return ResourceManager.GetString("Thank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say huge thank you.
        /// </summary>
        public static string Thank3 {
            get {
                return ResourceManager.GetString("Thank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your support!.
        /// </summary>
        public static string ThanksForYourSupport {
            get {
                return ResourceManager.GetString("ThanksForYourSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app .
        /// </summary>
        public static string ThisApp {
            get {
                return ResourceManager.GetString("ThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder before calendar event.
        /// </summary>
        public static string TimeBeforeEventReminder {
            get {
                return ResourceManager.GetString("TimeBeforeEventReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable &quot;{0}&quot; is already in saved.
        /// </summary>
        public static string TimetableAlreadySaved {
            get {
                return ResourceManager.GetString("TimetableAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached the end of timetable.
        /// </summary>
        public static string TimetableEndReached {
            get {
                return ResourceManager.GetString("TimetableEndReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable doesn&apos;t contain any events.
        /// </summary>
        public static string TimetableIsEmpty {
            get {
                return ResourceManager.GetString("TimetableIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable is already up-to-date.
        /// </summary>
        public static string TimetableLatest {
            get {
                return ResourceManager.GetString("TimetableLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables.
        /// </summary>
        public static string Timetables {
            get {
                return ResourceManager.GetString("Timetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable &quot;{0}&quot; has been saved.
        /// </summary>
        public static string TimetableSaved {
            get {
                return ResourceManager.GetString("TimetableSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable update.
        /// </summary>
        public static string TimetableUpdate {
            get {
                return ResourceManager.GetString("TimetableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable has been successfully updated: {0}.
        /// </summary>
        public static string TimetableUpdated {
            get {
                return ResourceManager.GetString("TimetableUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until break ({0}): {1}.
        /// </summary>
        public static string TimeUntilBreak {
            get {
                return ResourceManager.GetString("TimeUntilBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until {0} ({1}): {2}.
        /// </summary>
        public static string TimeUntilLesson {
            get {
                return ResourceManager.GetString("TimeUntilLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned off.
        /// </summary>
        public static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string UkrainianLanguage {
            get {
                return ResourceManager.GetString("UkrainianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University information update.
        /// </summary>
        public static string UniversityInfoUpdate {
            get {
                return ResourceManager.GetString("UniversityInfoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update university information from Cist?.
        /// </summary>
        public static string UniversityInfoUpdateConfirm {
            get {
                return ResourceManager.GetString("UniversityInfoUpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update university information. Please try again later..
        /// </summary>
        public static string UniversityInfoUpdateFail {
            get {
                return ResourceManager.GetString("UniversityInfoUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some information wasn&apos;t updated: {0}.
        /// </summary>
        public static string UniversityInfoUpdatePartiallyFail {
            get {
                return ResourceManager.GetString("UniversityInfoUpdatePartiallyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already downloaded the latest version of university information.
        /// </summary>
        public static string UniversityInfoUpToDate {
            get {
                return ResourceManager.GetString("UniversityInfoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close page without saving changes?.
        /// </summary>
        public static string UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all saved timetables?.
        /// </summary>
        public static string UpdateAllTimetables {
            get {
                return ResourceManager.GetString("UpdateAllTimetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update timetable.
        /// </summary>
        public static string UpdateTimetable {
            get {
                return ResourceManager.GetString("UpdateTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contribution supports development and doesn&apos;t let me fall into oblivion..
        /// </summary>
        public static string YourContribution {
            get {
                return ResourceManager.GetString("YourContribution", resourceCulture);
            }
        }
    }
}
