name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    name: Build ${{ matrix.configuration }}
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-quality: preview
    - uses: actions/checkout@v2
    - name: Install workload
      run: dotnet workload install maui-android
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
