name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    name: Build ${{ matrix.configuration }}
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v2
    - name: Install workload
      run: dotnet workload install maui-android --from-rollback-file aka.ms/dotnet/maui/preview.12.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
