name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd NureTimetable/NureTimetable.Android
        msbuild NureTimetable.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
